### ISSUE TITLE
Please publish 1.0.2 based on master

### ISSUE THREAD

**Issue by cscd98** [webgriffe/module-bootstrap-menu#3]
Hi,

The current version of theme-bootstrap requires version 1.x release. This repository needs a new release to be published. Please click on releases->new release->tag version 1.0.3 and release title 1.0.3

webgriffe/module-bootstrap-menu 1.0.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.8) does not satisfy that requirement.

https://github.com/webgriffe/theme-bootstrap/issues/13

**Comment by mmenozzi** [comment]
Done! Thank you!
